### ISSUE TITLE
java.lang.IllegalStateException: This operation is permitted on the event thread only;

### ISSUE THREAD

**Issue by gavinbarnard** [haveno-dex/haveno#1031]
Recevied java.lang.IllegalStateException: This operation is permitted on the event thread only; while idling on Buy screen.

```
Jun-11 13:00:48.106 [main] INFO  h.c.app.Version: Version{VERSION=1.0.7, P2P_NETWORK_VERSION=A, LOCAL_DB_VERSION=1, TRADE_PROTOCOL_VERSION=1, BASE_CURRENCY_NETWORK=0, getP2PNetworkId()=0A} 

Jun-11 13:00:48.106 [main] INFO  h.c.s.CommonSetup: Path to Haveno jar file: C:\Haveno\app\desktop-1.0.7-SNAPSHOT-all.jar 

...
Jun-12 11:41:08.874 [JavaFX Application Thread] INFO  h.d.c.c.c.PopOver: hide:200.0 ms 

Jun-12 11:41:09.701 [JavaFX Application Thread] INFO  h.d.c.c.c.PopOver: hide:200.0 ms 

Jun-12 11:41:12.077 [JavaFX Application Thread] INFO  h.d.c.c.c.PopOver: hide:200.0 ms 

Jun-12 11:41:24.246 [JavaFX Application Thread] INFO  h.d.c.c.c.PopOver: hide:200.0 ms 

Jun-12 11:41:24.869 [JavaFX Application Thread] INFO  h.d.c.c.c.PopOver: hide:200.0 ms 

Jun-12 11:41:33.223 [JavaFX Application Thread] INFO  h.d.c.c.c.PopOver: hide:200.0 ms 

Jun-12 11:41:37.485 [JavaFX Application Thread] INFO  h.d.c.c.c.PopOver: hide:200.0 ms 

Jun-12 11:41:49.639 [JavaFX Application Thread] INFO  h.d.c.c.c.PopOver: hide:200.0 ms 

Jun-12 11:47:13.062 [Thread-17443] ERROR h.c.s.CommonSetup: Uncaught Exception from thread Thread-17443 

Jun-12 11:47:13.062 [Thread-17443] ERROR h.c.s.CommonSetup: throwableMessage= This operation is permitted on the event thread only; currentThread = Thread-17443 

Jun-12 11:47:13.062 [Thread-17443] ERROR h.c.s.CommonSetup: throwableClass= class java.lang.IllegalStateException 

Jun-12 11:47:13.064 [Thread-17443] ERROR h.c.s.CommonSetup: Stack trace:
java.lang.IllegalStateException: This operation is permitted on the event thread only; currentThread = Thread-17443

	at javafx.graphics/com.sun.glass.ui.Application.checkEventThread(Unknown Source)

	at javafx.graphics/com.sun.glass.ui.View.getNativeView(Unknown Source)

	at javafx.graphics/com.sun.glass.ui.win.WinAccessible.get_HostRawElementProvider(Unknown Source)

	at javafx.graphics/com.sun.glass.ui.win.WinAccessible.UiaRaiseAutomationEvent(Native Method)

	at javafx.graphics/com.sun.glass.ui.win.WinAccessible.sendNotification(Unknown Source)

	at javafx.graphics/javafx.scene.Node.notifyAccessibleAttributeChanged(Unknown Source)

	at javafx.controls/javafx.scene.control.TableView$TableViewFocusModel.lambda$new$0(Unknown Source)

	at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)

	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)

	at javafx.base/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(Unknown Source)

	at javafx.base/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(Unknown Source)

	at javafx.base/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)

	at javafx.base/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)

	at javafx.controls/javafx.scene.control.TableView$TableViewFocusModel.setFocusedCell(Unknown Source)

	at javafx.controls/javafx.scene.control.TableView$TableViewFocusModel.focus(Unknown Source)

	at javafx.controls/javafx.scene.control.TableView$TableViewFocusModel.lambda$new$1(Unknown Source)

	at javafx.base/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)

	at javafx.base/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)

	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)

	at javafx.base/javafx.collections.ObservableListBase.fireChange(Unknown Source)

	at javafx.base/javafx.collections.ListChangeBuilder.commit(Unknown Source)

	at javafx.base/javafx.collections.ListChangeBuilder.endChange(Unknown Source)

	at javafx.base/javafx.collections.ObservableListBase.endChange(Unknown Source)

	at javafx.base/javafx.collections.transformation.SortedList.sourceChanged(Unknown Source)

	at javafx.base/javafx.collections.transformation.TransformationList.lambda$getListener$0(Unknown Source)

	at javafx.base/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)

	at javafx.base/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)

	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)

	at javafx.base/javafx.collections.ObservableListBase.fireChange(Unknown Source)

	at javafx.base/javafx.collections.ListChangeBuilder.commit(Unknown Source)

	at javafx.base/javafx.collections.ListChangeBuilder.endChange(Unknown Source)

	at javafx.base/javafx.collections.ObservableListBase.endChange(Unknown Source)

	at javafx.base/javafx.collections.transformation.FilteredList.sourceChanged(Unknown Source)

	at javafx.base/javafx.collections.transformation.TransformationList.lambda$getListener$0(Unknown Source)

	at javafx.base/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)

	at javafx.base/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)

	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)

	at javafx.base/javafx.collections.ObservableListBase.fireChange(Unknown Source)

	at javafx.base/javafx.collections.ListChangeBuilder.commit(Unknown Source)

	at javafx.base/javafx.collections.ListChangeBuilder.endChange(Unknown Source)

	at javafx.base/javafx.collections.ObservableListBase.endChange(Unknown Source)

	at javafx.base/javafx.collections.ModifiableObservableListBase.remove(Unknown Source)

	at javafx.base/javafx.collections.ModifiableObservableListBase.remove(Unknown Source)

	at haveno.desktop.main.offer.offerbook.OfferBook.removeOffer(OfferBook.java:183)

	at haveno.desktop.main.offer.offerbook.OfferBook$1.onRemoved(OfferBook.java:109)

	at haveno.core.offer.OfferBookService.lambda$updateAffectedOffers$5(OfferBookService.java:307)

	at java.base/java.lang.Thread.run(Unknown Source)

 

Jun-12 11:47:13.066 [Thread-17443] ERROR h.c.s.CommonSetup: Uncaught Exception from thread Thread-17443 

Jun-12 11:47:13.066 [Thread-17443] ERROR h.c.s.CommonSetup: throwableMessage= This operation is permitted on the event thread only; currentThread = Thread-17443 

Jun-12 11:47:13.066 [Thread-17443] ERROR h.c.s.CommonSetup: throwableClass= class java.lang.IllegalStateException 

Jun-12 11:47:13.066 [Thread-17443] ERROR h.c.s.CommonSetup: Stack trace:
java.lang.IllegalStateException: This operation is permitted on the event thread only; currentThread = Thread-17443

	at javafx.graphics/com.sun.glass.ui.Application.checkEventThread(Unknown Source)

	at javafx.graphics/com.sun.glass.ui.View.getNativeView(Unknown Source)

	at javafx.graphics/com.sun.glass.ui.win.WinAccessible.get_HostRawElementProvider(Unknown Source)

	at javafx.graphics/com.sun.glass.ui.win.WinAccessible.UiaRaiseAutomationEvent(Native Method)

	at javafx.graphics/com.sun.glass.ui.win.WinAccessible.sendNotification(Unknown Source)

	at javafx.graphics/javafx.scene.Node.notifyAccessibleAttributeChanged(Unknown Source)

	at javafx.controls/javafx.scene.control.TableView$TableViewFocusModel.lambda$new$0(Unknown Source)

	at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)

	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)

	at javafx.base/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(Unknown Source)

	at javafx.base/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(Unknown Source)

	at javafx.base/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)

	at javafx.base/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)

	at javafx.controls/javafx.scene.control.TableView$TableViewFocusModel.setFocusedCell(Unknown Source)

	at javafx.controls/javafx.scene.control.TableView$TableViewFocusModel.focus(Unknown Source)

	at javafx.controls/javafx.scene.control.TableView$TableViewFocusModel.lambda$new$1(Unknown Source)

	at javafx.base/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)

	at javafx.base/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)

	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)

	at javafx.base/javafx.collections.ObservableListBase.fireChange(Unknown Source)

	at javafx.base/javafx.collections.ListChangeBuilder.commit(Unknown Source)

	at javafx.base/javafx.collections.ListChangeBuilder.endChange(Unknown Source)

	at javafx.base/javafx.collections.ObservableListBase.endChange(Unknown Source)

	at javafx.base/javafx.collections.transformation.SortedList.sourceChanged(Unknown Source)

	at javafx.base/javafx.collections.transformation.TransformationList.lambda$getListener$0(Unknown Source)

	at javafx.base/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)

	at javafx.base/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)

	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)

	at javafx.base/javafx.collections.ObservableListBase.fireChange(Unknown Source)

	at javafx.base/javafx.collections.ListChangeBuilder.commit(Unknown Source)

	at javafx.base/javafx.collections.ListChangeBuilder.endChange(Unknown Source)

	at javafx.base/javafx.collections.ObservableListBase.endChange(Unknown Source)

	at javafx.base/javafx.collections.transformation.FilteredList.sourceChanged(Unknown Source)

	at javafx.base/javafx.collections.transformation.TransformationList.lambda$getListener$0(Unknown Source)

	at javafx.base/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)

	at javafx.base/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)

	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)

	at javafx.base/javafx.collections.ObservableListBase.fireChange(Unknown Source)

	at javafx.base/javafx.collections.ListChangeBuilder.commit(Unknown Source)

	at javafx.base/javafx.collections.ListChangeBuilder.endChange(Unknown Source)

	at javafx.base/javafx.collections.ObservableListBase.endChange(Unknown Source)

	at javafx.base/javafx.collections.ModifiableObservableListBase.add(Unknown Source)

	at java.base/java.util.AbstractList.add(Unknown Source)

	at haveno.desktop.main.offer.offerbook.OfferBook$1.onAdded(OfferBook.java:91)

	at haveno.core.offer.OfferBookService.lambda$updateAffectedOffers$5(OfferBookService.java:308)

	at java.base/java.lang.Thread.run(Unknown Source)

 

Jun-12 11:47:13.069 [Thread-17482] ERROR h.c.s.CommonSetup: Uncaught Exception from thread Thread-17482 

Jun-12 11:47:13.069 [Thread-17482] ERROR h.c.s.CommonSetup: throwableMessage= This operation is permitted on the event thread only; currentThread = Thread-17482 

Jun-12 11:47:13.069 [Thread-17482] ERROR h.c.s.CommonSetup: throwableClass= class java.lang.IllegalStateException 

Jun-12 11:47:13.070 [Thread-17482] ERROR h.c.s.CommonSetup: Stack trace:
java.lang.IllegalStateException: This operation is permitted on the event thread only; currentThread = Thread-17482

	at javafx.graphics/com.sun.glass.ui.Application.checkEventThread(Unknown Source)

	at javafx.graphics/com.sun.glass.ui.View.getNativeView(Unknown Source)

	at javafx.graphics/com.sun.glass.ui.win.WinAccessible.get_HostRawElementProvider(Unknown Source)

	at javafx.graphics/com.sun.glass.ui.win.WinAccessible.UiaRaiseAutomationEvent(Native Method)

	at javafx.graphics/com.sun.glass.ui.win.WinAccessible.sendNotification(Unknown Source)

	at javafx.graphics/javafx.scene.Node.notifyAccessibleAttributeChanged(Unknown Source)

	at javafx.controls/javafx.scene.control.TableView$TableViewFocusModel.lambda$new$0(Unknown Source)

	at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)

	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)

	at javafx.base/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(Unknown Source)

	at javafx.base/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(Unknown Source)

	at javafx.base/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)

	at javafx.base/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)

	at javafx.controls/javafx.scene.control.TableView$TableViewFocusModel.setFocusedCell(Unknown Source)

	at javafx.controls/javafx.scene.control.TableView$TableViewFocusModel.focus(Unknown Source)

	at javafx.controls/javafx.scene.control.TableView$TableViewFocusModel.lambda$new$1(Unknown Source)

	at javafx.base/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)

	at javafx.base/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)

	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)

	at javafx.base/javafx.collections.ObservableListBase.fireChange(Unknown Source)

	at javafx.base/javafx.collections.ListChangeBuilder.commit(Unknown Source)

	at javafx.base/javafx.collections.ListChangeBuilder.endChange(Unknown Source)

	at javafx.base/javafx.collections.ObservableListBase.endChange(Unknown Source)

	at javafx.base/javafx.collections.transformation.SortedList.sourceChanged(Unknown Source)

	at javafx.base/javafx.collections.transformation.TransformationList.lambda$getListener$0(Unknown Source)

	at javafx.base/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)

	at javafx.base/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)

	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)

	at javafx.base/javafx.collections.ObservableListBase.fireChange(Unknown Source)

	at javafx.base/javafx.collections.ListChangeBuilder.commit(Unknown Source)

	at javafx.base/javafx.collections.ListChangeBuilder.endChange(Unknown Source)

	at javafx.base/javafx.collections.ObservableListBase.endChange(Unknown Source)

	at javafx.base/javafx.collections.transformation.FilteredList.sourceChanged(Unknown Source)

	at javafx.base/javafx.collections.transformation.TransformationList.lambda$getListener$0(Unknown Source)

	at javafx.base/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)

	at javafx.base/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)

	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)

	at javafx.base/javafx.collections.ObservableListBase.fireChange(Unknown Source)

	at javafx.base/javafx.collections.ListChangeBuilder.commit(Unknown Source)

	at javafx.base/javafx.collections.ListChangeBuilder.endChange(Unknown Source)

	at javafx.base/javafx.collections.ObservableListBase.endChange(Unknown Source)

	at javafx.base/javafx.collections.ModifiableObservableListBase.remove(Unknown Source)

	at javafx.base/javafx.collections.ModifiableObservableListBase.remove(Unknown Source)

	at haveno.desktop.main.offer.offerbook.OfferBook.removeOffer(OfferBook.java:183)

	at haveno.desktop.main.offer.offerbook.OfferBook$1.onRemoved(OfferBook.java:109)

	at haveno.core.offer.OfferBookService.lambda$updateAffectedOffers$5(OfferBookService.java:307)

	at java.base/java.lang.Thread.run(Unknown Source)

 

Jun-12 11:47:26.150 [JavaFX Application Thread] INFO  h.c.u.DesktopUtil: Trying to exec: cmd = explorer args = %s file = "C:\Users\\AppData\Roaming\Haveno-reto\haveno.log" 

Jun-12 11:47:26.154 [JavaFX Application Thread] INFO  h.c.u.DesktopUtil: Process is running. 
```

**Comment by woodser** [comment]
Fixed by https://github.com/haveno-dex/haveno/pull/1052
