### ISSUE TITLE
ERROR: Cannot invoke "javafx.scene.Node.getScene()" because "n" is null

### ISSUE THREAD

**Issue by XMRZombie** [haveno-dex/haveno#1363]
This happens when a UI component is not properly initialized or added to the scene graph before layout operations occur.
```
[JavaFX Application Thread] ERROR haveno.common.setup.CommonSetup: Uncaught Exception from thread JavaFX Application Thread, error=Cannot invoke "javafx.scene.Node.getScene()" because "n" is null
 java.lang.NullPointerException: Cannot invoke "javafx.scene.Node.getScene()" because "n" is null
	at javafx.graphics/javafx.scene.layout.Region.getSnapScaleX(Region.java:264)
	at javafx.graphics/javafx.scene.layout.Region.layoutInArea(Region.java:2534)
	at javafx.controls/javafx.scene.control.SkinBase.layoutInArea(SkinBase.java:965)
	at javafx.controls/javafx.scene.control.SkinBase.layoutInArea(SkinBase.java:850)
	at javafx.controls/javafx.scene.control.skin.TableViewSkinBase.layoutChildren(TableViewSkinBase.java:458)
	at javafx.controls/javafx.scene.control.Control.layoutChildren(Control.java:612)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1208)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1215)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1215)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1215)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1215)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1215)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1215)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1215)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1215)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1215)
	at javafx.graphics/javafx.scene.Scene.doLayoutPass(Scene.java:594)
	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2600)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:401)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:400)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:430)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:592)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:572)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:565)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:352)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:263)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

**Comment by XMRZombie** [comment]
I built haveno from source and always making sure to shutdown the client before doing $ make clean

**Comment by woodser** [comment]
I think we're stuck without a way to reproduce it.

**Comment by woodser** [comment]
Hopefully fixed with https://github.com/haveno-dex/haveno/commit/c1b17cf61257a492da3137d9f23e496dbea729bc.
