### ISSUE TITLE
ERROR: Rejected tasks (java.util.concurrent)

### ISSUE THREAD

**Issue by XMRZombie** [haveno-dex/haveno#1365]
- The error:
```
[JavaFX Application Thread] ERROR h.c.s.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
[JavaFX Application Thread] ERROR h.c.s.CommonSetup: throwableMessage= Task java.util.concurrent.FutureTask@1ffb4eee[Not completed, task = haveno.network.p2p.network.TorNetworkNodeNetlayer$$Lambda/0x00007fd13067f200@2950aa99] rejected from java.util.concurrent.ThreadPoolExecutor@5b09835c[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0] 
[JavaFX Application Thread] ERROR h.c.s.CommonSetup: throwableClass= class java.util.concurrent.RejectedExecutionException 
[JavaFX Application Thread] ERROR h.c.s.CommonSetup: Stack trace:
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@1ffb4eee[Not completed, task = haveno.network.p2p.network.TorNetworkNodeNetlayer$$Lambda/0x00007fd13067f200@2950aa99] rejected from java.util.concurrent.ThreadPoolExecutor@5b09835c[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1376)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at java.base/java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:790)
	at haveno.network.p2p.network.TorNetworkNodeNetlayer.createTorAndHiddenService(TorNetworkNodeNetlayer.java:137)
	at haveno.network.p2p.network.TorNetworkNode.start(TorNetworkNode.java:63)
	at haveno.network.p2p.network.TorNetworkNodeNetlayer.start(TorNetworkNodeNetlayer.java:62)
	at haveno.network.p2p.P2PService.start(P2PService.java:162)
	at haveno.core.app.P2PNetworkSetup.init(P2PNetworkSetup.java:133)
	at haveno.core.app.HavenoSetup.startP2pNetworkAndWallet(HavenoSetup.java:425)
	at haveno.core.app.HavenoSetup.step3(HavenoSetup.java:322)
	at haveno.network.p2p.storage.P2PDataStorage.lambda$readFromResources$2(P2PDataStorage.java:217)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:192)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
	at javafx.base/javafx.beans.binding.ObjectBinding.invalidate(ObjectBinding.java:192)
	at javafx.base/com.sun.javafx.binding.BindingHelperObserver.invalidated(BindingHelperObserver.java:52)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:147)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:104)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at haveno.network.p2p.storage.P2PDataStorage.lambda$readFromResources$3(P2PDataStorage.java:221)
	at haveno.network.p2p.storage.persistence.AppendOnlyDataStoreService.lambda$readFromResources$0(AppendOnlyDataStoreService.java:66)
	at haveno.network.p2p.storage.persistence.HistoricalDataStoreService.lambda$readFromResources$2(HistoricalDataStoreService.java:160)
	at haveno.common.UserThread.lambda$execute$0(UserThread.java:64)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:263)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
This error occurs when a task is submitted to an executor service that has already been terminated.

**Comment by woodser** [comment]
I think that logging the exception could be ok in this case, because it's correctly showing that a task did not complete, due to the ExecutorService being terminated (due to application shutting down), but there is no functional problem.

Otherwise in order to fix this, we would need to globally check if the application is shutting down and ignore the expected errors from every ExecutorService in this case?

**Comment by XMRZombie** [comment]
If it was a logic ending on a task then that ok, I was searching in my logs for bugs to report
