### ISSUE TITLE
Fix error when arbitrator gives all payout to one trader

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#162]
In the desktop application, the arbitrator may give maximum payout to one trader and 0 payout to the other trader:

![image](https://user-images.githubusercontent.com/13068859/141658107-109af5b3-5911-4e8a-91e8-1a4024c3dadd.png)

Currently, this results in the error: -20: destination amount is zero, with the following stacktrace.

<details>
  <summary>Stacktrace</summary>
 
```
-20: destination amount is zero
RPC request: 'transfer' with params: {"get_tx_key":true,"account_index":0,"get_tx_metadata":true,"destinations":[{"amount":"208000000000","address":"79mD8QoxdVCJLSUTn1vVX1AaT6GtEkTuKMn3BPjAHjYJ2TNrs56KKaAPKrhsiXk8o3AHJzie2LJkfajGVrzunLkTHFnvqp6"},{"amount":"0","address":"77PUtBsVGosKU3k5S984ssEGgbzvsR2EE5Q96ER8xbRai76tKu2uct8FDyXqMG39eCNoUzSujFksj5DRtPt7vMTr3NJfsgF"}],"get_tx_hex":true,"do_not_relay":true}
	at monero.common.MoneroRpcConnection.validateRpcResponse(MoneroRpcConnection.java:453)
	at monero.common.MoneroRpcConnection.sendJsonRequest(MoneroRpcConnection.java:259)
	at monero.common.MoneroRpcConnection.sendJsonRequest(MoneroRpcConnection.java:216)
	at monero.wallet.MoneroWalletRpc.createTxs(MoneroWalletRpc.java:1188)
	at monero.wallet.MoneroWalletDefault.createTx(MoneroWalletDefault.java:308)
	at monero.wallet.MoneroWalletRpc.createTx(MoneroWalletRpc.java:92)
	at bisq.core.support.dispute.arbitration.ArbitrationManager.arbitratorCreatesDisputedPayoutTx(ArbitrationManager.java:621)
	at bisq.core.support.dispute.arbitration.ArbitrationManager.onArbitratorPayoutTxRequest(ArbitrationManager.java:426)
	at bisq.core.support.dispute.arbitration.ArbitrationManager.onSupportMessage(ArbitrationManager.java:136)
	at bisq.core.support.SupportManager.lambda$applyMessages$6(SupportManager.java:309)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.core.support.SupportManager.applyMessages(SupportManager.java:306)
	at bisq.core.support.SupportManager.tryApplyMessages(SupportManager.java:128)
	at bisq.core.support.SupportManager.lambda$new$0(SupportManager.java:73)
	at bisq.network.p2p.P2PService.lambda$onMessage$8(P2PService.java:384)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.network.p2p.P2PService.lambda$onMessage$9(P2PService.java:384)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:201)
	at bisq.network.p2p.P2PService.onMessage(P2PService.java:383)
	at bisq.network.p2p.network.NetworkNode.lambda$onMessage$6(NetworkNode.java:392)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at bisq.network.p2p.network.NetworkNode.onMessage(NetworkNode.java:392)
	at bisq.network.p2p.network.Connection.lambda$onMessage$9(Connection.java:436)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.network.p2p.network.Connection.lambda$onMessage$10(Connection.java:436)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
```
</details>

The problem appears to be caused by adding a destination with the 0 amount to [this payment configuration](https://github.com/haveno-dex/haveno/blob/4000fdc1e581b5608ae1d68f783000559f514913/core/src/main/java/bisq/core/support/dispute/arbitration/ArbitrationManager.java#L624). Instead, the destination should only be added if the payout is greater than 0.

## Steps to reproduce

1. [Run a local network](https://github.com/haveno-dex/haveno/blob/master/docs/installing.md).
2. Start a trade between Alice and Bob so they have deposited to multisig.
3. Mine 10 block so the deposit transactions unlock.
4. Open a dispute from either Alice or Bob.
5. Go to the arbitrator desktop application > Support > Arbitrators tickets > double click a support ticket > Close ticket
6. Select "max payout to BTC buyer" and enter a reason for the dispute and some text in the summary field.
7. Close the ticket.
8. Observe the above error.

**Comment by woodser** [comment]
Closed by #177
