### ISSUE TITLE
Dockerize deamons

### ISSUE THREAD

**Issue by erciccione** [haveno-dex/haveno#284]
This is needed to make the life of the UI team simpler.

We need to run on Docker:

- seednode
- arbitrator-daemon
- alice-daemon
- bob-daemon
- Monero

It will also help for #21

**Comment by erciccione** [comment]
I'll take care and prioritize this in the next days. I'm not a Docker expert, so any suggestion is appreciated.

**Comment by erciccione** [comment]
@CristianMG: Hey there. Copy pasting this message from #haveno-dev on matrix:

"The UI development team is starting to work on Haveno and would very much like to use a dockerized version of the Haveno daemons. I checked your old link at https://github.com/CristianMG/haveno/tree/master/docker but unfortunately it's no longer there. it seems you were close to opening a PR? do you still have that work available? by the way, the arbitrator now runs as a daemon instead of a desktop application, so that should help"

Any help would be appreciated :)

**Comment by CryptoGrampy** [comment]
Copying and pasting from Matrix :)

You could probably create a haveno image with an ubuntu/openjdk11 base (haveno/dockerfiles/haveno/Dockerfile)... maybe use a separate image/dependencies for monerod (haveno/dockerfiles/monerod/Dockerfile) and then use docker compose and overwrite your starting commands to do something like: 

really rough sketch of a potential docker-compose.yml:
`version: '3'
    services:
      aliced:
        build: haveno/dockerfiles/haveno
        command/entrypoint: ["make alice-daemon"]
        ports:
          - 1234:1234
      bobd:
        build: haveno/dockerfiles/haveno
        command: ["make bob-daemon"] 
        ports: 
          - 1234:1234
      seed:
        command: ["make seed-thing"]
      monerod:
        build: haveno/dockerfiles/monerod // Different image?
        ports:
          - 18089:18089
        volumes:
          - bitmonero:/home/monero/.bitmonero
    volumes: 
      - bitmonero`
   
I imagine monero will need a lot more dependencies to build, and you'll need to have a volume for blockchain data, etc.  Probably good to reference Seth's simple-monerod docker image.  I haven't done much docker startup command overriding so i'm not sure what's possible.

**Comment by erciccione** [comment]
I just pushed what i got so far: https://github.com/erciccione/haveno/tree/docker

This is still very much work in progress and there is still stuff to do:

- the network settings are temporary and needed to resolve a local connection problem
- all containers run as expected, but we need somebody familiar with docker-compose commands for things like sending commands to a container (for example, to start mining on one of the 2 nodes)
- format is messed. I'm leaving that for last
- the daemons seem to not be able to connect to the Monero daemon. I have to look into how the Docker network works.

I'm not familiar with Docker and have no prior knowledge of docker-compose, so any help is appreciated.

**Comment by erciccione** [comment]
After running a command in either of the 2 containers with a monero node (`node1` or `node2`) using `docker-compose run $service $command`, I keep getting `Error: Couldn't connect to daemon: 127.0.0.1:18081` even if the port i set is not 18081. This doesn't change, no matter what port i set. Trying to figure it out.

**Comment by erciccione** [comment]
Found the issue thanks to moneromooo's help. Will update soon.

**Comment by erciccione** [comment]
I pushed a draft at #297

**Comment by abouolia** [comment]
@erciccione Tried to run the docker compose containers and everything worked well, but when trying to run the test cases of haveno-ts, all tests fail because the `arbitrator` doesn't run. how can we solve that issue?

**Comment by abouolia** [comment]
Even try to get Monero transactions get that error.

```
May-31 16:56:51.453 [grpc-default-executor-10] ERROR b.d.grpc.GrpcWalletsService:  monero.common.MoneroRpcError: 
	at monero.common.MoneroRpcConnection.validateRpcResponse(MoneroRpcConnection.java:489)
	at monero.common.MoneroRpcConnection.sendJsonRequest(MoneroRpcConnection.java:295)
	at monero.common.MoneroRpcConnection.sendJsonRequest(MoneroRpcConnection.java:252)
	at monero.wallet.MoneroWalletRpc.getTransfersAux(MoneroWalletRpc.java:2047)
	at monero.wallet.MoneroWalletRpc.getTxs(MoneroWalletRpc.java:954)
	at monero.wallet.MoneroWalletDefault.getTxs(MoneroWalletDefault.java:217)
	at monero.wallet.MoneroWalletRpc.getTxs(MoneroWalletRpc.java:92)
	at monero.wallet.MoneroWalletDefault.getTxs(MoneroWalletDefault.java:197)
	at monero.wallet.MoneroWalletRpc.getTxs(MoneroWalletRpc.java:92)
	at bisq.core.api.CoreWalletsService.getXmrTxs(CoreWalletsService.java:179)
	at bisq.core.api.CoreApi.getXmrTxs(CoreApi.java:285)
	at bisq.daemon.grpc.GrpcWalletsService.getXmrTxs(GrpcWalletsService.java:170)
	at bisq.proto.grpc.WalletsGrpc$MethodHandlers.invoke(WalletsGrpc.java:1397)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

monero.common.MoneroRpcError: 
	at monero.common.MoneroRpcConnection.validateRpcResponse(MoneroRpcConnection.java:489)
	at monero.common.MoneroRpcConnection.sendJsonRequest(MoneroRpcConnection.java:295)
	at monero.common.MoneroRpcConnection.sendJsonRequest(MoneroRpcConnection.java:252)
	at monero.wallet.MoneroWalletRpc.getTransfersAux(MoneroWalletRpc.java:2047)
	at monero.wallet.MoneroWalletRpc.getTxs(MoneroWalletRpc.java:954)
	at monero.wallet.MoneroWalletDefault.getTxs(MoneroWalletDefault.java:217)
	at monero.wallet.MoneroWalletRpc.getTxs(MoneroWalletRpc.java:92)
	at monero.wallet.MoneroWalletDefault.getTxs(MoneroWalletDefault.java:197)
	at monero.wallet.MoneroWalletRpc.getTxs(MoneroWalletRpc.java:92)
	at bisq.core.api.CoreWalletsService.getXmrTxs(CoreWalletsService.java:179)
	at bisq.core.api.CoreApi.getXmrTxs(CoreApi.java:285)
	at bisq.daemon.grpc.GrpcWalletsService.getXmrTxs(GrpcWalletsService.java:170)
	at bisq.proto.grpc.WalletsGrpc$MethodHandlers.invoke(WalletsGrpc.java:1397)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by woodser** [comment]
These services are now dockerized and run as part of our CI tests. Please re-open if we continue to have problems.
