### ISSUE TITLE
Support ARM64 / aarch64 [1 XMR]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno#792]
This issue requests running Haveno in ARM64 / aarch64.

Currently, running in Ubuntu 22.04.2 ARM64 gives this error:

```
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: /home/woodser/.openjfx/cache/16/libprism_es2.so: /home/woodser/.openjfx/cache/16/libprism_es2.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)
java.lang.UnsatisfiedLinkError: /home/woodser/.openjfx/cache/16/libprism_es2.so: /home/woodser/.openjfx/cache/16/libprism_es2.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2450)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2506)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2705)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2635)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1850)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:214)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:194)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:135)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:53)
	at com.sun.prism.es2.ES2Pipeline.lambda$static$0(ES2Pipeline.java:69)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.prism.es2.ES2Pipeline.<clinit>(ES2Pipeline.java:51)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:91)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

See related issue running Haveno in Manjaro aarch64: https://github.com/haveno-dex/haveno/issues/790

**Comment by preland** [comment]
(The reason for this is that javafx just doesn't exist for arm64 before 17)

Another large note is that JFoenix doesn't support any javafx version after 16 (what a coincidence). There appears to be some attempts to continue it past 17, (the most promising one I see is (this one)[https://github.com/ihmcrobotics/JFoenix-Group]; however I can't currently get it to work using jitpack

**Comment by woodser** [comment]
FYI we've updated to JDK and JFX 21 on the master branch.

The app is working for me as a native ARM64 app on macOS.

However getting an error on Ubuntu ARM64 VM running on macOS (even after updating TOR with #794):

```
Mar-12 13:04:36.585 [ERR] ERROR o.b.netlayer.tor.Tor: rosetta error: failed to open elf at /lib64/ld-linux-x86-64.so.2 
Mar-12 13:04:36.685 [ERR] ERROR o.b.netlayer.tor.Tor:   
Mar-12 13:04:36.686 [StartTor] ERROR h.n.p2p.network.TorNetworkNode: Starting tor node failed org.berndpruenster.netlayer.tor.TorCtlException: Could not setup Tor
	at org.berndpruenster.netlayer.tor.NativeTor.<init>(NativeTor.kt:106)
	at org.berndpruenster.netlayer.tor.NativeTor.<init>(NativeTor.kt:55)
	at org.berndpruenster.netlayer.tor.NativeTor.<init>(NativeTor.kt)
	at haveno.network.p2p.network.NewTor.getTor(NewTor.java:107)
	at haveno.network.p2p.network.TorNetworkNode.lambda$createTorAndHiddenService$10(TorNetworkNode.java:172)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.IOException: java.io.IOException: Tor exited with value 133
	at org.berndpruenster.netlayer.tor.TorContext.installAndStartTorOp(TorContext.kt:392)
	at org.berndpruenster.netlayer.tor.NativeTor.<init>(NativeTor.kt:66)
	... 8 common frames omitted
Caused by: java.io.IOException: Tor exited with value 133
	at org.berndpruenster.netlayer.tor.TorContext.installAndStartTorOp(TorContext.kt:354)
	... 9 common frames omitted
```

**Comment by woodser** [comment]
I created a new VM without x86 emulation, and now I'm getting this error on Ubuntu ARM64 from the master branch:

`Syntax error: Unterminated quoted string`

Hopefully others will see the same. Here's the full stacktrace:

```
org.berndpruenster.netlayer.tor.TorCtlException: Could not setup Tor
	at org.berndpruenster.netlayer.tor.NativeTor.<init>(NativeTor.kt:106)
	at org.berndpruenster.netlayer.tor.NativeTor.<init>(NativeTor.kt:55)
	at org.berndpruenster.netlayer.tor.NativeTor.<init>(NativeTor.kt)
	at haveno.network.p2p.network.NewTor.getTor(NewTor.java:107)
	at haveno.network.p2p.network.TorNetworkNode.lambda$createTorAndHiddenService$10(TorNetworkNode.java:172)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.IOException: java.io.IOException: Tor exited with value 2
	at org.berndpruenster.netlayer.tor.TorContext.installAndStartTorOp(TorContext.kt:392)
	at org.berndpruenster.netlayer.tor.NativeTor.<init>(NativeTor.kt:66)
	... 8 common frames omitted
Caused by: java.io.IOException: Tor exited with value 2
	at org.berndpruenster.netlayer.tor.TorContext.installAndStartTorOp(TorContext.kt:354)
	... 9 common frames omitted
Mar-14 19:16:13.892 [JavaFX Application Thread] ERROR h.core.app.P2PNetworkSetup: onSetupFailed 
Mar-14 19:16:13.895 [ERR] ERROR o.b.netlayer.tor.Tor: /home/woodser/.local/share/Haveno/xmr_stagenet/tor/tor: 2: Syntax error: Unterminated quoted string
```

**Comment by preland** [comment]
Interesting; is that file (...../xmr_stagenet/tor/tor) a bash script? The reason I ask is that the error _strongly_ implies that it is, but the equivalent file on my system is not a bash script.

**Comment by woodser** [comment]
> Interesting; is that file (...../xmr_stagenet/tor/tor) a bash script? The reason I ask is that the error _strongly_ implies that it is, but the equivalent file on my system is not a bash script.

It's a binary.

**Comment by woodser** [comment]
Very likely the wrong tor binary is being downloaded for arm64.

**Comment by preland** [comment]
Looking into it, there actually isn't an official ARM64 tor-binary (see [here](https://gitlab.torproject.org/tpo/applications/tor-browser-build/-/issues/32355)). 

There have been unofficial builds, and there have been several PRs attempting to add it, with none of them being accepted. Sadly, it seems the tor project has had [reasons to avoid adding arm64 support in the past](https://forum.torproject.org/t/tor-browser-for-arm-linux/5240).

**Comment by preland** [comment]
MacOS ARM64 is supported, and since the current tor-binary implementation grabs the universal binary, there (shouldn't) be any issues for MacOS Apple Silicon.

**Comment by woodser** [comment]
Can confirm it's working on macOS ARM64, but didn't know if the in-built rosetta translation is helping it work.

Whereas we get an error on Ubuntu ARM64 (virtualized on macOS), and yeah it seems they don't release the tor binary for that platform.

**Comment by phytohydra** [comment]
Most linux distributions have a tor daemon binary package already in the repos, including on arm64.  Maintaining just the tor daemon is much easier than porting and packaging the entire Tor Browser.

Instead of getting your own copy of the binary directly from Tor Project, you can make tor daemon a build/install dependency, have your install script set up the environment for the private instance you're going to be running, with your own data directory and torrc file, then at runtime invoke the system binary with `--torrc-file <your torrc>` to run your private instance with the config you need.  I think that's the way you're supposed to be doing it.

**Comment by NorrinRadd** [comment]
> FYI we've updated to JDK and JFX 21 on the master branch.
> 
> The app is working for me as a native ARM64 app on macOS.
> 
> However getting an error on Ubuntu ARM64 VM running on macOS (even after updating TOR with #794):
> 
> ```
> Mar-12 13:04:36.567 [StartTor] INFO  o.b.netlayer.tor.Tor: Starting Tor 
> Mar-12 13:04:36.585 [ERR] ERROR o.b.netlayer.tor.Tor: rosetta error: failed to open elf at /lib64/ld-linux-x86-64.so.2 
> Mar-12 13:04:36.685 [ERR] ERROR o.b.netlayer.tor.Tor:   
> Mar-12 13:04:36.686 [StartTor] ERROR h.n.p2p.network.TorNetworkNode: Starting tor node failed org.berndpruenster.netlayer.tor.TorCtlException: Could not setup Tor
> 	at org.berndpruenster.netlayer.tor.NativeTor.<init>(NativeTor.kt:106)
> 	at org.berndpruenster.netlayer.tor.NativeTor.<init>(NativeTor.kt:55)
> 	at org.berndpruenster.netlayer.tor.NativeTor.<init>(NativeTor.kt)
> 	at haveno.network.p2p.network.NewTor.getTor(NewTor.java:107)
> 	at haveno.network.p2p.network.TorNetworkNode.lambda$createTorAndHiddenService$10(TorNetworkNode.java:172)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
> 	at java.base/java.lang.Thread.run(Thread.java:1583)
> Caused by: java.io.IOException: java.io.IOException: Tor exited with value 133
> 	at org.berndpruenster.netlayer.tor.TorContext.installAndStartTorOp(TorContext.kt:392)
> 	at org.berndpruenster.netlayer.tor.NativeTor.<init>(NativeTor.kt:66)
> 	... 8 common frames omitted
> Caused by: java.io.IOException: Tor exited with value 133
> 	at org.berndpruenster.netlayer.tor.TorContext.installAndStartTorOp(TorContext.kt:354)
> 	... 9 common frames omitted
> ```
> 
> This suggests something in the app is still using x86 version?

The commit to upgrade to jfx 21 did not resolve the prism error for me.

**Comment by U65535F** [comment]
@woodser is this open?

**Comment by woodser** [comment]
This issue still applies and is not fixed on Linux ARM afaik.

**Comment by NorrinRadd** [comment]
@woodser wouldn't it be expected to see many different errors similar to the Tor error, due to native binaries? Tor likely isn't the only issue. Won't all native binaries generate something like this and require fixes? I'm not sure what that number of native binaries is.  If you have an idea, you'd be in a better position to scope this effort and give a heads-up to anyone that's considering working on this.

**Comment by woodser** [comment]
Actually I think it's just tor and the monero binaries.

**Comment by boldsuck** [comment]
> Most linux distributions have a tor daemon binary package already in the repos, including on arm64. Maintaining just the tor daemon is much easier than porting and packaging the entire Tor Browser.

These people can use Haveno with DirectBindTor or ExternalTor and do not need Tor with Haveno
Entire Tor Browser is fetched because Haveno needs the pluggable transports, too. (lyrebird, snowflake,..)

**Comment by woodser** [comment]
Issue is resolved by https://github.com/haveno-dex/haveno/pull/1665 bounty is paid.
