### ISSUE TITLE
Cannot read the array length because "seeds" is null

### ISSUE THREAD

**Issue by nsec1** [haveno-dex/haveno#883]
Error opening app using user1-desktop-stagenet on master branch:
```
java.lang.NullPointerException: Cannot read the array length because "seeds" is null
	at haveno.network.Socks5DnsDiscovery.buildDiscoveries(Socks5DnsDiscovery.java:74)
	at haveno.network.Socks5DnsDiscovery.<init>(Socks5DnsDiscovery.java:70)
	at haveno.network.Socks5DnsDiscovery.<init>(Socks5DnsDiscovery.java:60)
	at haveno.network.Socks5MultiDiscovery.<init>(Socks5MultiDiscovery.java:68)
	at haveno.core.xmr.nodes.XmrNetworkConfig.proposePeers(XmrNetworkConfig.java:65)
	at haveno.core.xmr.setup.WalletsSetup.configPeerNodes(WalletsSetup.java:329)
	at haveno.core.xmr.setup.WalletsSetup.initialize(WalletsSetup.java:216)
	at haveno.core.app.WalletAppSetup.init(WalletAppSetup.java:197)
	at haveno.core.app.HavenoSetup.initWallet(HavenoSetup.java:449)
	at haveno.core.app.P2PNetworkSetup$2.onTorNodeReady(P2PNetworkSetup.java:145)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at haveno.network.p2p.P2PService.onTorNodeReady(P2PService.java:246)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at haveno.network.p2p.network.TorNetworkNode.lambda$createTorAndHiddenService$2(TorNetworkNode.java:176)
	at haveno.common.UserThread.lambda$execute$0(UserThread.java:64)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:263)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by woodser** [comment]
Fixed by https://github.com/haveno-dex/haveno/pull/885
